# Uncomment this line to define a global platform for your project
# platform :ios, '8.0'
# Uncomment this line if you're using Swift
# use_frameworks!

target 'RogueKitDemo' do

pod 'Masonry'
pod 'MBProgressHUD', '~> 1.0.0'
pod 'AFNetworking'
pod 'TOWebViewController'
pod 'UICKeyChainStore'

end

